### ISSUE TITLE
tk27- Add media query to decrease the jumbotron height when in responsive view

### ISSUE THREAD

**Issue by khubaibshah786** [dpaul93/Group-3-Project-1#39]

**Comment by dpaul93** [comment]
When in responsive view the writing is overlapping with the jumbotron. Some investigation required but could be worthwhile to separate the text from the jumbo so they are in different sections.

**Comment by dpaul93** [comment]
Look into either media queries or bootstrap to ensure the sizing is still presentable and features don't over lap and the smallest of screen sizes. (Mobile M and Mobile S)
